unit STEFIHC;

interface

const

  hcAbout                = 1503;
  hcCancelBtn            = 4001;
  hcChDirDBox            = 2002;
  hcCloseBox             = 4004;
  hcColors               = 1302;
  hcColorsDBox           = 2006;
  hcContents             = 1501;
  hcDAbout               = 2007;
  hcEdit                 = 1202;
  hcEditGraph            = 11;
  hcErrorHelp            = 4015;
  hcErrorMessages        = 4010;
  hcErrorPrinting        = 4014;
  hcErrorReading         = 4012;
  hcErrorShow            = 4017;
  hcErrorWriting         = 4013;
  hcFile                 = 1100;
  hcGraph                = 1200;
  hcHelp                 = 1500;
  hcHelpContents         = 1000;
  hcHelpUsingHelp        = 1001;
  hcHistory              = 4002;
  hcKeyboard             = 4009;
  hcMenu                 = 1002;
  hcMouse                = 1301;
  hcMouseDBox            = 2005;
  hcNoContext            = 0;
  hcNoGraphics           = 4016;
  hcNoMem                = 4011;
  hcOkBtn                = 4000;
  hcOpenDBox             = 2000;
  hcOpenText             = 1101;
  hcOptions              = 1300;
  hcPrint                = 1102;
  hcReport               = 1203;
  hcReportDBox           = 2003;
  hcSaveAsDBox           = 2001;
  hcScrollBars           = 4007;
  hcShow                 = 1204;
  hcShowDBox             = 2004;
  hcTextViewer           = 4008;
  hcTitleBar             = 4006;
  hcUsingHelp            = 1502;
  hcView                 = 1201;
  hcViewWindow           = 10;
  hcWindow               = 1400;
  hcWindowBasics         = 4003;
  hcZoomBox              = 4005;

implementation

end.
