INSERT INTO dolgozo
    VALUES ('17405241111', 'Toth Balint',
	    '1039 Bp. Kabar u.7.',            '1873943', 01, 06);

INSERT INTO dolgozo
    VALUES ('17001011111', 'Glazser Bozso',
	    '1111 Bp. Harap u. 3.',           '2222222', 01, 06);

INSERT INTO dolgozo
    VALUES ('17501032222', 'Kis Pal',
	    '1234 Bp. Voroshadsereg u 1.',    '3333333', 02, 05);

INSERT INTO dolgozo
    VALUES ('17501013333', 'Borz',
	    '1101 Bp. Fo ut 33',              '4444444', 01, 09);
