INSERT INTO telephely
    VALUES (01, '1031 Bp. Szentendrei ut 107.',   '1234567');
INSERT INTO telephely
    VALUES (02, '1111 Bp. Muegyetem rakpart 3.',   '9999999');
INSERT INTO telephely
    VALUES (03, '1212 Bp. Vizimano u. 34.',        '7654321');
INSERT INTO telephely
    VALUES (04, '1142 Bp. Voros hads. utja 108.',  '3141592');

INSERT INTO beosztas
    VALUES (01, 'ugyvezeto igazgato',              500000);
INSERT INTO beosztas
    VALUES (02, 'igazgatohelyettes',               400000);
INSERT INTO beosztas
    VALUES (03, 'fokonyvelo',                      200000);
INSERT INTO beosztas
    VALUES (04, 'telephely vezeto',                300000);
INSERT INTO beosztas
    VALUES (05, 'osztalyvezeto',                   150000);
INSERT INTO beosztas
    VALUES (06, 'ugynok',                          70000);
INSERT INTO beosztas
    VALUES (07, 'titkarno',                        40000);
INSERT INTO beosztas
    VALUES (08, 'ejjelior',                        35000);
INSERT INTO beosztas
    VALUES (09, 'portas',                          25000);
INSERT INTO beosztas
    VALUES (10, 'takarito',                        25000);
