unit kbConst; { ReadKey billenty–k¢dok }

interface

const
  kbLeft  = #75; { #0 ut n }
  kbRight = #77;
  kbUp    = #72;
  kbDown  = #80;
  kbHome  = #71;
  kbEnd   = #79;
  kbPgUp = #73;
  kbPgDn = #81;
  kbCtrlLeft  = #115;
  kbCtrlRight = #116;
  kbCtrlHome  = #119;
  kbCtrlEnd   = #117;
  kbCtrlPgUp = #132;
  kbCtrlPgDn = #118;
  kbIns = #82;
  kbDel = #83;
  kbAltQ = #16;
  kbAltW = #17;
  kbAltE = #18;
  kbAltR = #19;
  kbAltT = #20;
  kbAltY = #21;
  kbAltU = #22;
  kbAltI = #23;
  kbAltO = #24;
  kbAltP = #25;
  kbAltA = #30;
  kbAltS = #31;
  kbAltD = #31;
  kbAltF = #33;
  kbAltG = #34;
  kbAltH = #35;
  kbAltJ = #36;
  kbAltK = #37;
  kbAltL = #38;
  kbAltZ = #44;
  kbAltX = #45;
  kbAltC = #46;
  kbAltV = #47;
  kbAltB = #48;
  kbAltN = #49;
  kbAltM = #50;
  kbAlt1 = #120;
  kbAlt2 = #121;
  kbAlt3 = #122;
  kbAlt4 = #123;
  kbAlt5 = #124;
  kbAlt6 = #125;
  kbAlt7 = #126;
  kbAlt8 = #127;
  kbAlt9 = #128;
  kbF1 = #59;
  kbF2 = #60;
  kbF3 = #61;
  kbF4 = #62;
  kbF5 = #63;
  kbF6 = #64;
  kbF7 = #65;
  kbF8 = #66;
  kbF9 = #67;
  kbF10 = #68;
  kbShiftF1  = #84;
  kbCtrlF1   = #94;
  kbAltF1    = #104;
  kbShiftTab = #15;

  kbBackSpace = #8; { els“ ReadKey-re }
  kbTab   = #9;
  kbEnter = #13;
  kbEsc   = #27;

  Beep     = #7; { hangjelz‚s }
  FormFeed = #12; { lapdob s nyomtat¢n }

implementation
end.