#REM  Ascii Textfile Master - dem¢ include f†jl (LEVEL.INC)
#REM  LevÇlben elìfordul¢ sz¢fordulatok

#REM magyarul:

#define NYIT1 Tisztelt Uram!
#define NYIT2 Tisztelt Hîlgyem / Uram!
#define NYIT3 Kedves @c°mzett@!
#define îRÅL1 Nagyon îrÅltem legut¢bbi levelednek.
#define BOCS1 Ne haragudj, hogy mindeddig nem v†laszoltam, de 
#define V†LASZ1 V†rom v†laszod!
#define Z†R1 Sz°vÇlyes Ådvîzlettel:

#REM angolul:

#define OPEN1 Dear Sir,
#define OPEN2 Dear Madam / Sir,
#define OPEN3 Dear @c°mzett@,
#define ASK1 Could you please
#define ASK2 Would you be so kind to
#define REPLY1 I look forward to hearing from you.
#define REPLY2 Please write soon!
#define CLOSE1 Yours sincerelly,
#define CLOSE2 Yours faithfully,
