#REM  Ascii Textfile Master - dem¢ include f†jl (SAJAT.INC)
#REM  SzemÇlyes adatok

#define sNÇV T¢th B†lint
#define sKOR 19
#define sMAG 181 cm
#define sSZEMSZ°N kÇk
#define sHAJSZ°N barna
#define sC°M 1039 Budapest, Kabar u. 7. V. 27.
#define sV†ros Budapest
#define sTEL 187-3943
#define sSZÅLD†TUM 1974. m†jus 24.
#define sSZEMSZ†M 1 740524 ****
#define sANYU Diczku Olga
#define sFOGL egyetemi hallgat¢
#define sBME Budapesti Mñszaki Egyetem
#define sVILL VillamosmÇrnîki Çs Informatikai Kar
#define sINFO Mñszaki Informatika Szak
#define sÇVF 1. Çvfolyam, 2. fÇlÇv
#define sTK 3. tanul¢kîr
#define sTELJ @sNÇv@, @sBME@, @sVILL@, @sINFO@, @sÇVF@, @sTK@
