unit CVHELP;

interface

const

  hcAbout                = 1134;
  hcAsciiViewer          = 1122;
  hcAsciiWindow          = 2509;
  hcAssemble             = 1109;
  hcCancelBtn            = 10001;
  hcCloseBox             = 2502;
  hcColors               = 1115;
  hcCompile              = 1108;
  hcContents             = 1131;
  hcDAbout               = 10119;
  hcDisAssembler         = 1120;
  hcDMemFill             = 10115;
  hcDMemFind             = 10116;
  hcDMemLoad             = 10117;
  hcDMemSave             = 10118;
  hcDump                 = 1121;
  hcDumpWindow           = 2508;
  hcEdit                 = 1101;
  hcEditor               = 2507;
  hcEditWindow           = 2506;
  hcFCChDirBtn           = 10109;
  hcFCChDirDBox          = 2020;
  hcFCDirName            = 10107;
  hcFCDirTree            = 10108;
  hcFCRevertBtn          = 10110;
  hcFile                 = 1100;
  hcFind                 = 1104;
  hcFOFileOpenDBox       = 2000;
  hcFOFiles              = 10101;
  hcFOName               = 10100;
  hcFOOpenBtn            = 10102;
  hcFSFiles              = 10106;
  hcFSFileSaveAsDBox     = 2010;
  hcFSName               = 10105;
  hcHelp                 = 1130;
  hcHelpContents         = 1000;
  hcHelpIndex            = 1001;
  hcHelpUsingHelp        = 1002;
  hcHistory              = 2500;
  hcHowToUseHelp         = 1003;
  hcIndex                = 1132;
  hcLoadDesktop          = 1117;
  hcMakePRG              = 1110;
  hcMakeT64              = 1111;
  hcMemFill              = 1126;
  hcMemFind              = 1127;
  hcMemLoad              = 1128;
  hcMemory               = 1125;
  hcMemSave              = 1129;
  hcMouse                = 1114;
  hcNoContext            = 0;
  hcOCColorsDBox         = 10114;
  hcOkBtn                = 10000;
  hcOMMouseDBox          = 10113;
  hcOptions              = 1112;
  hcOutput               = 1124;
  hcRegisters            = 1123;
  hcRegsWindow           = 2510;
  hcReplace              = 1105;
  hcReport               = 1113;
  hcRun                  = 1107;
  hcSaveDesktop          = 1118;
  hcScrollBars           = 2505;
  hcSearch               = 1103;
  hcSearchAgain          = 1106;
  hcSFFindDBox           = 10111;
  hcShowClip             = 1102;
  hcSRReplaceDBox        = 10112;
  hcTitleBar             = 2504;
  hcToggleVideo          = 1116;
  hcUsingHelp            = 1133;
  hcWindow               = 1119;
  hcWindowBasics         = 2501;
  hcZoomBox              = 2503;

implementation

end.
